import { filterAuthoringFontFamilies } from './font-authoring-policy';

export interface FontEntry {
  name: string;
  file: string;
  format?: 'woff2' | 'woff';
  unicodeRange?: string;
}

export const FONT_LIST: readonly FontEntry[] = [
  { name: '함초롬돋움', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '함초롬바탕', file: '/fonts/NotoSerifKR-Regular.woff2' },
  { name: '함초롱돋움', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '함초롱바탕', file: '/fonts/NotoSerifKR-Regular.woff2' },
  { name: '한컴돋움', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '한컴바탕', file: '/fonts/NotoSerifKR-Regular.woff2' },
  { name: '새돋움', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '새바탕', file: '/fonts/NotoSerifKR-Regular.woff2' },
  { name: 'HY헤드라인M', file: '/fonts/NotoSansKR-Bold.woff2' },
  { name: 'HYHeadLine M', file: '/fonts/NotoSansKR-Bold.woff2' },
  { name: 'HYHeadLine Medium', file: '/fonts/NotoSansKR-Bold.woff2' },
  { name: 'HY견고딕', file: '/fonts/NotoSansKR-Bold.woff2' },
  { name: 'HYGothic-Extra', file: '/fonts/NotoSansKR-Bold.woff2' },
  { name: 'HY그래픽', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: 'HYGraphic-Medium', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: 'HY그래픽M', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: 'HY견명조', file: '/fonts/NotoSerifKR-Bold.woff2' },
  { name: 'HYMyeongJo-Extra', file: '/fonts/NotoSerifKR-Bold.woff2' },
  { name: 'HY신명조', file: '/fonts/NotoSerifKR-Regular.woff2' },
  { name: 'HY중고딕', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '양재튼튼체B', file: '/fonts/NotoSansKR-Bold.woff2' },
  { name: 'Malgun Gothic', file: '/fonts/Pretendard-Regular.woff2' },
  { name: '맑은 고딕', file: '/fonts/Pretendard-Regular.woff2' },
  { name: '돋움', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '돋움체', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '굴림', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '굴림체', file: '/fonts/D2Coding-Regular.woff2' },
  { name: '새굴림', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: '바탕', file: '/fonts/NotoSerifKR-Regular.woff2' },
  { name: '바탕체', file: '/fonts/D2Coding-Regular.woff2' },
  { name: '궁서', file: '/fonts/GowunBatang-Regular.woff2' },
  { name: '궁서체', file: '/fonts/GowunBatang-Regular.woff2' },
  { name: '새궁서', file: '/fonts/GowunBatang-Regular.woff2' },
  { name: '나눔고딕', file: '/fonts/NanumGothic-Regular.woff2' },
  { name: '나눔명조', file: '/fonts/NanumMyeongjo-Regular.woff2' },
  { name: '나눔고딕코딩', file: '/fonts/NanumGothicCoding-Regular.woff2' },
  { name: 'Palatino Linotype', file: '/fonts/NotoSerifKR-Regular.woff2' },
  { name: 'Noto Sans KR', file: '/fonts/NotoSansKR-Regular.woff2' },
  { name: 'Noto Serif KR', file: '/fonts/NotoSerifKR-Regular.woff2' },
  { name: 'Pretendard', file: '/fonts/Pretendard-Regular.woff2' },
  { name: 'Pretendard Thin', file: '/fonts/Pretendard-Thin.woff2' },
  { name: 'Pretendard ExtraLight', file: '/fonts/Pretendard-ExtraLight.woff2' },
  { name: 'Pretendard Light', file: '/fonts/Pretendard-Light.woff2' },
  { name: 'Pretendard Medium', file: '/fonts/Pretendard-Medium.woff2' },
  { name: 'Pretendard SemiBold', file: '/fonts/Pretendard-SemiBold.woff2' },
  { name: 'Pretendard Bold', file: '/fonts/Pretendard-Bold.woff2' },
  { name: 'Pretendard ExtraBold', file: '/fonts/Pretendard-ExtraBold.woff2' },
  { name: 'Pretendard Black', file: '/fonts/Pretendard-Black.woff2' },
  { name: 'D2Coding', file: '/fonts/D2Coding-Regular.woff2' },
  { name: '해피니스 산스 레귤러', file: '/fonts/Happiness-Sans-Regular.woff2' },
  { name: 'Happiness Sans Regular', file: '/fonts/Happiness-Sans-Regular.woff2' },
  { name: '해피니스 산스 볼드', file: '/fonts/Happiness-Sans-Bold.woff2' },
  { name: 'Happiness Sans Bold', file: '/fonts/Happiness-Sans-Bold.woff2' },
  { name: '해피니스 산스 타이틀', file: '/fonts/Happiness-Sans-Title.woff2' },
  { name: 'Happiness Sans Title', file: '/fonts/Happiness-Sans-Title.woff2' },
  { name: '해피니스 산스 VF', file: '/fonts/HappinessSansVF.woff2' },
  { name: 'Happiness Sans VF', file: '/fonts/HappinessSansVF.woff2' },
  { name: 'Cafe24 Ssurround Bold', file: '/fonts/Cafe24Ssurround-v2.0.woff2' },
  { name: '카페24 슈퍼매직', file: '/fonts/Cafe24Supermagic-Regular-v1.0.woff2' },
  { name: 'Cafe24 Supermagic', file: '/fonts/Cafe24Supermagic-Regular-v1.0.woff2' },
  { name: 'Latin Modern Math', file: '/fonts/LatinModernMath-Regular.woff2' },
  { name: 'SpoqaHanSans', file: '/fonts/SpoqaHanSans-Regular.woff2' },
  { name: '고운바탕', file: '/fonts/GowunBatang-Regular.woff2' },
  { name: '고운돋움', file: '/fonts/GowunDodum-Regular.woff2' },
];

export const REGISTERED_FONTS = new Set(
  filterAuthoringFontFamilies(FONT_LIST.map((font) => font.name)),
);
